digital_portfolio/main/routes.py
from flask import render_template, url_for, redirect, Blueprint, flash
from flask_login import current_user
from digital_portfolio.models import Portfolio

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    # if current_user.is_authenticated:
    #     if Portfolio.query.filter_by(current_user.username).first():
    #         flash('You have had a portfolio already')
    #         return redirect(url_for('users.user_portfolio'))
    return render_template('home.html')

@main.route("/about")
def about():
    return render_template('about.html', title='About')

digital_portfolio/portfolio/routes.py
from flask import (render_template, url_for, flash, redirect, \
    request, abort, Blueprint)
from flask_login import current_user, login_required
from digital_portfolio import db
from digital_portfolio.models import Portfolio, Comments
from digital_portfolio.portfolio.forms import PorfolioForm
from datetime import datetime

portfolio = Blueprint('portfolio', __name__)

@portfolio.route("/create_portfolio", methods=['Get','POST'])
def create_portfolio():
    if current_user.is_authenticated:
        if Portfolio.query.filter_by(author=current_user).first():
            flash('You have had a portfolio already', 'info')
            return redirect(url_for('users.user_portfolio', username=current_user.username))
    else:
        flash('You should log in first.', 'info')
        return redirect(url_for('users.login'))
    form = PorfolioForm()
    if form.validate_on_submit():
        portfolio = Portfolio(name=form.name.data, \
            tech_skills=form.tech_skills.data, \
                work_produced=form.work_produced.data, \
                    experience=form.experience.data, \
                        contact=form.contact.data, \
                            author=current_user)
        db.session.add(portfolio)
        db.session.commit()
        flash('Your portfolio has been created!', 'success')
        return redirect(url_for('users.user_portfolio', username=current_user.username))
    return render_template('create_portfolio.html', title='Create a portfolio', 
                           form=form, legend='Create Your Portfolio!')
    
@portfolio.route("/<string:username>/delete", methods=['POST'])
@login_required
def delete_portfolio(username):
    portfolio = Portfolio.query.filter_by(author=current_user).first_or_404()
    if portfolio.author.username != username: 
        abort(403)
    Comments.query.filter_by(portfolio_id=portfolio.id).delete()
    db.session.delete(portfolio)
    db.session.commit()
    flash('Your portfolio has been deleted. You can create a new one now.', 'success')
    return redirect(url_for('main.home'))

@portfolio.route("/<string:username>/edit", methods=['GET', 'POST'])
@login_required
def edit_portfolio(username):
    portfolio = Portfolio.query.filter_by(author=current_user).first_or_404()
    if portfolio.author.username != username:
        abort(403)
    update = PorfolioForm()
    if update.validate_on_submit(): 
        portfolio.name = update.name.data
        portfolio.contact = update.contact.data
        portfolio.tech_skills = update.tech_skills.data
        portfolio.work_produced = update.work_produced.data
        portfolio.experience = update.experience.data
        portfolio.date_edited = datetime.now()
        db.session.commit()
        flash('Your portfolio has been updated', 'success')
        return redirect(url_for('users.user_portfolio', username=username))
    elif request.method == 'GET':
        update.name.data =  portfolio.name
        update.contact.data = portfolio.contact
        update.tech_skills.data = portfolio.tech_skills
        update.work_produced.data = portfolio.work_produced
        update.experience.data = portfolio.experience
    return render_template('create_portfolio.html', title='Edit the Portfolio',
                           form=update, legend='Edit the Portfolio')

digital_portfolio/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from digital_portfolio import db, bcrypt
from digital_portfolio.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from digital_portfolio.portfolio.forms import CommentForm
from digital_portfolio.models import User, Portfolio, Comments
from flask_login import login_user, current_user, logout_user, login_required

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in and make your portfolio', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)
    
@users.route("/portfolio/<string:username>", methods=['GET','POST'])
def user_portfolio(username):
    user = User.query.filter_by(username=username).first_or_404()
    portfolio = Portfolio.query.filter_by(author=user).first()
    if portfolio is None:
        flash('Please create one portfolio first', 'warning')
        return redirect(url_for('portfolio.create_portfolio'))
    comments = Comments.query.filter_by(portfolio_id=portfolio.id).order_by(Comments.comment_time.desc()).all()
    form = CommentForm()
    if form.validate_on_submit():
        if form.content.data:
            if current_user.is_authenticated:
                comment = Comments(content=form.content.data, portfolio_id=portfolio.id, username=current_user.username)
                db.session.add(comment)
                db.session.commit()
                flash('Your comment has been send.', 'success')
                return redirect(url_for('users.user_portfolio', username=username))
            else:
                flash('You must log in first!', 'danger')
                return redirect(url_for('users.login'))
        else:
            form.content.errors.append('Comment content cannot be empty!')
    return render_template('user_portfolio.html', portfolio=portfolio, 
                           comments=comments, form=form)

digital_portfolio/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <br>
    <h1>{{ current_user.username }}</h1>
    <h3>{{ current_user.email }}</h3>
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

digital_portfolio/templates/create_portfolio.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.contact.label(class="form-control-label") }}
                    {% if form.contact.errors %}
                        {{ form.contact(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.contact.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.contact(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.tech_skills.label(class="form-control-label") }}
                    {% if form.tech_skills.errors %}
                    {{ form.tech_skills(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.tech_skills.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.tech_skills(class="form-control form-control-lg") }}
                {% endif %}
                </div>
                <div class="form-group">
                    {{ form.work_produced.label(class="form-control-label") }}
                    {% if form.work_produced.errors %}
                    {{ form.work_produced(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.work_produced.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.work_produced(class="form-control form-control-lg") }}
                {% endif %}
                </div>
                <div class="form-group">
                    {{ form.experience.label(class="form-control-label") }}
                    {% if form.experience.errors %}
                    {{ form.experience(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.experience.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.experience(class="form-control form-control-lg") }}
                {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

digital_portfolio/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    <div class="col-lg-8 intro">
        <p>Here, you can make your own portfolio with a brief form...</p>
    </div>
    <div class="col-lg-4 button">
        <span>Do you wanna have a try?</span>
        <a class="btn btn-light create" href="{{ url_for('portfolio.create_portfolio') }}">Create Your Portfolio</a>
    </div>
</div>
<div class="home">
    <div class="sample">
        <p id="greetings">Hi! I am Jingjing Wu.</p>
        <span class="contact">Contact Me<br>wuj0710@gmail.com</span>
        <div class="portfolio">
            <div>
                <img class="ts_icon icon" src="../../static/pics/online-test.png">
                <p class="title">Technical skills</p>
                <p class="content">I have solid experience in Python and Java, which I've used to create various web applications and tackle different programming challenges. My work includes building back-end functionality, designing user interfaces, and implementing key features like authentication and data management. I'm also comfortable using Flask for Python web development and have worked with Java frameworks like Spring.</p>
            </div>
            <div>
                <img class="wd_icon icon" src="../../static/pics/hard-work.png">
                <p class="title">Work Produced to Date</p>
                <p class="content">I've developed a post website application that lets users create, edit, and delete posts, as well as view posts made by specific users. It's designed to be simple and intuitive while offering core features that people expect in a blog-like platform. Another project I worked on is a portfolio website application, which provides customizable templates for users to build their personal portfolios.It also allows users to leave comments on others' portfolios. </p>
            </div>
            <div>
                <img class="e_icon icon" src="../../static/pics/best-employee.png">
                <p class="title">Experience</p>
                <p class="content">● 2024.3 - 2024.6 Gamepic
                    <br>- Involved in both game planning and testing
                    <br>- Identified bugs and suggested improvements to enhance the player experience
                    <br>- Engaged in game localization
                </p>
            </div>
            <p class="edit_time">Last Edited: 2024-12-28 17:00</p>
            <div class="comment">
                <span class="comment_username">Jingjing Wu</span><br>
                <span class="comment_content">Feel free to leave comments!</span>
                <span class="comment_time">Commented on 2024-12-28</span>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

digital_portfolio/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Afacad+Flux:wght@100..1000&family=Birthstone&family=Delius&family=Gaegu&family=Lexend:wght@100..900&family=Quicksand:wght@300..700&family=Tinos:ital,wght@0,400;0,700;1,400;1,700&display=swap"
        rel="stylesheet">
    <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Portfolio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" href="{{ url_for('main.home') }}">Home</a>
                    {% if current_user.is_authenticated %}
                    <a class="nav-link active"
                        href="{{ url_for('users.user_portfolio', username=current_user.username) }}">My Portfolio</a>
                    <a class="nav-link active" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-link active" href="{{ url_for('users.logout') }}">Log Out</a>
                    {% else %}
                    <a class="nav-link active" href="{{ url_for('users.login') }}">Log In</a>
                    <a class="nav-link active" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.rtl.min.css"
        integrity="sha384-dpuaG1suU0eT09tx5plTaGMLBsfDLzUCCUXOY2j/LSvXYuG6Bqs43ALlhIqAJVRb" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
</head>

<body>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
</body>

</html>

digital_portfolio/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

digital_portfolio/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Log In</a>
        </small>
    </div>
{% endblock content %}

digital_portfolio/templates/user_portfolio.html
{% extends "layout.html" %}
{% block content %}
<div class="personal_page">
    <div class="head">
        <p id="greetings">Hi, I am {{ portfolio.name }}.</p>
        <span class="contact">Contact Me<br>{{ portfolio.contact }}</span>
    </div>
    <div class="portfolio">
        <div>
            <img class="ts_icon icon" src="../../static/pics/online-test.png">
            <p class="title">Technical skills</p>
            <p class="content">{{ portfolio.tech_skills }}</p>
        </div>
        <div>
            <img class="wd_icon icon" src="../../static/pics/hard-work.png">
            <p class="title">Work Produced to Date</p>
            <p class="content">{{ portfolio.work_produced }}</p>
        </div>
        <div>
            <img class="e_icon icon" src="../../static/pics/best-employee.png">
            <p class="title">Experience</p>
            <p class="content">{{ portfolio.experience }}</p>
        </div>
        <p class="edit_time">Last Edited: {{ portfolio.date_edited.strftime('%Y-%m-%d %H:%M') }}</p>
    </div>
</div>
{% if comments %}
{% for comment in comments %}
<div class="comment">
    <a href="{{ url_for('users.user_portfolio', username=comment.username) }}" class="comment_username">{{ comment.username }}</a>
    <br>
    <span class="comment_content">{{ comment.content }}</span>
    <br>
    <span class="comment_time">Commented on {{ comment.comment_time.strftime('%Y-%m-%d') }}</span>
</div>
{% endfor %}
{% endif %}
<div class="input_comment">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.content.label(class="form-control-label") }}
            {% if form.content.errors %}
            {{ form.content(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.content.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.content(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info btn-sm") }}
        </div>
    </form>
</div>
{% if portfolio.author == current_user %}
<div class="edit">
    <p>These buttons can be seen only by the author.</p>
    <a href="{{ url_for('portfolio.edit_portfolio', username=current_user.username) }}"
        class="btn btn-primary btn-sm">Edit the
        Portfolio</a>
    <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete the
        Portfolio</button>
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <!-- Modal -->
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deleteModalLabel">Want to delete it?</h1>
                    <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
                </div>
                <div class="modal-body">
                    All the comments will be deleted too. This change will NOT be reversible.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{{ url_for('portfolio.delete_portfolio', username=current_user.username) }}"
                        method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                    {% endif %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </div>
</div>